<b><h1><center>CLEANING AND ANALYSIS ON SCRAPED DATA</center></h1></b>

<hr>

<b><h1>Import Libraries</h1></b>

In [57]:
import numpy as np
import pandas as pd

<b><h1>Load Dataset</h1></b>

In [58]:
df = pd.read_csv("../Data/raw_data.csv")

In [59]:
df.shape

(960, 7)

In [60]:
df.head()

,Name,Price,Ram,System,SSD,Processor,Display
0,Lenovo Ultra 5 225U Intel Core Ultra 5 225U - ...,"₹1,10,999",16 GB DDR5 RAM,Windows 11 Operating System,1 TB SSD,Intel Core Ultra 5 Processor,40.64 cm (16 inch) Display
1,Acer Aspire Lite AMD Ryzen 3 Quad Core 5400U -...,"₹38,990",8 GB DDR4 RAM,Windows 11 Operating System,256 GB SSD,AMD Ryzen 3 Quad Core Processor,39.62 cm (15.6 Inch) Display
2,Neopticon BrowseBook Intel Celeron Dual Core N...,"₹19,590",4 GB LPDDR4 RAM,64 bit Windows 11 Home Operating System,256 GB SSD,Intel Celeron Dual Core Processor,35.81 cm (14.1 Inch) Display
3,Ultimus Pro Intel Celeron Dual Core N4020 - (4...,"₹15,399",4 GB DDR4 RAM,Windows 11 Operating System,NaN,Intel Celeron Dual Core Processor,35.81 cm (14.1 Inch) Display
4,ASUS Vivobook 14 (2026) Intel Core i3 13th Gen...,"₹49,990",8 GB DDR4 RAM,Windows 11 Home Operating System,512 GB SSD,Intel Core i3 Processor (13th Gen),35.56 cm (14 inch) Display

<b><h1>Data Cleaning</h1></b>

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 960 entries, 0 to 959
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       960 non-null    str
 1   Price      960 non-null    str
 2   Ram        960 non-null    str
 3   System     960 non-null    str
 4   SSD        909 non-null    str
 5   Processor  960 non-null    str
 6   Display    960 non-null    str
dtypes: str(7)
memory usage: 264.9 KB

In [62]:
df.isna().sum()

Name          0
Price         0
Ram           0
System        0
SSD          51
Processor     0
Display       0
dtype: int64

In [63]:
df.dropna(inplace=True)

In [64]:
df.isna().sum()

Name         0
Price        0
Ram          0
System       0
SSD          0
Processor    0
Display      0
dtype: int64

In [65]:

df.duplicated().sum()

np.int64(110)

In [66]:
df.drop_duplicates(inplace=True)

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
df.shape

(799, 7)

In [69]:
# Extracting Brand name from Name column
df["Brand"]=df["Name"].str.split().str[0]

In [70]:
# Removing symobl and comma from Price 
df["Price"]=df["Price"].str.replace("₹", "").str.replace(",", "").astype(int)

In [71]:
# Extracting only ram from Ram column
df["Ram"]=df["Ram"].str.split().str[:2].str.join(" ")

In [72]:
# Extracting only ssd from SSD column
df["SSD"]=df["SSD"].str.split().str[:2].str.join(" ")

In [73]:
# Extracting processor name from Processor column
df["Processor"]=df["Processor"].str.split().str[:2].str.join(" ")

In [74]:
# Extracting only size in cm from Display column
df["Display"]=df["Display"].str.split().str[:2].str.join(" ")

In [75]:
# Extracting model name from Name column
df["Model"]=df["Name"].str.split().str[1]

In [76]:
# Ordering the columns
df = df[['Brand', 'Model', 'Processor', 'Ram', 'SSD', 'Price', 'Display']]

In [77]:
df.head()

       Brand       Model      Processor    Ram     SSD   Price   Display
0     Lenovo       Ultra     Intel Core  16 GB    1 TB  110999  40.64 cm
1       Acer      Aspire      AMD Ryzen   8 GB  256 GB   38990  39.62 cm
2  Neopticon  BrowseBook  Intel Celeron   4 GB  256 GB   19590  35.81 cm
4       ASUS    Vivobook     Intel Core   8 GB  512 GB   49990  35.56 cm
5       ASUS         ROG     Intel Core  32 GB    2 TB  499990  40.64 cm

In [78]:
df.info()

<class 'pandas.DataFrame'>
Index: 799 entries, 0 to 959
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Brand      799 non-null    object
 1   Model      799 non-null    object
 2   Processor  799 non-null    object
 3   Ram        799 non-null    object
 4   SSD        799 non-null    object
 5   Price      799 non-null    int64
 6   Display    799 non-null    object
dtypes: int64(1), object(6)
memory usage: 49.9+ KB

<b><h1>Data Analysis</h1></b>

In [79]:
# Which brand has highest price 
brand_price = df.groupby("Brand")["Price"].max().sort_values(ascending=False)
brand_price

Brand
ASUS          499990
DELL          440861
Apple         359900
MSI           347990
Lenovo        228490
GIGABYTE      222750
Samsung       214990
Acer          199990
HP            195210
MICROSOFT     156622
Colorful      139999
Infinix       129990
MOTOROLA       79990
ZEBRONICS      78999
Avita          60990
acer           58600
Ultimus        49998
WarnerCann     43686
walker         30000
Neopticon      19590
Name: Price, dtype: int64

In [80]:
# which processor has highest price
proc_price=df.groupby("Processor")["Price"].max().sort_values(ascending=False)
proc_price

Processor
Intel Core          499990
AMD Ryzen           370998
Apple M5            359900
Apple M1            239900
Snapdragon X        176000
Intel Ryzen         135000
Apple M3            134900
Apple M2            109900
Apple A18            89900
Processor: Intel     68990
Intel Snapdragon     66411
AMD Athlon           52990
Intel Pentium        52890
Intel Celeron        52839
AMD Dual             39119
Name: Price, dtype: int64

In [81]:
# is ssd depond on price
ssd_price=df.groupby("SSD")["Price"].max().sort_values(ascending=False)
ssd_price

SSD
2 TB      499990
1 TB      440861
512 GB    179900
256 GB    147622
RAM &      68990
500 GB     41990
128 GB     30000
Name: Price, dtype: int64

In [82]:
# is ram depond on price
ram_price=df.groupby("Ram")["Price"].max().sort_values(ascending=False)
ram_price

Ram
32 GB    499990
24 GB    359900
16 GB    347990
8 GB     179900
12 GB     80090
RAM &     68990
4 GB      52839
Name: Price, dtype: int64

In [83]:
# is screensize depond on price
display_price=df.groupby("Display")["Price"].max().sort_values(ascending=False)
display_price

Display
40.64 cm          499990
34.04 cm          370998
35.56 cm          359900
43.94 cm          347990
39.62 cm          320926
43.18 cm          304990
36.07 cm          239900
40.89 cm          195210
38.86 cm          189998
34.54 cm          185900
33.78 cm          179900
30.48 cm          156622
33.02 cm          134900
36.83 cm          109358
34.29 cm          107999
85.8 cm            88999
2.54 cm            87890
38.35 cm           71990
Display: 15.6"     68990
38.1 cm            68939
35.81 cm           57538
39.37 cm           52990
29.46 cm           39550
Name: Price, dtype: int64

<b><h1>Save Cleaned Data</h1></b>

In [84]:

df.to_csv("../Data/cleaned_data.csv", index=False)
print("Successfully Saved")

Successfully Saved

<b><h1><center>END</center></h1></b>

<HR>